---
- import_tasks: cleanup.yml
  when: systemd_networkd_cleanup | bool

- import_tasks: config.yml

- name: Make sure systemd-resolved is installed
  become: true
  ansible.builtin.package:
    name: systemd-resolved
    state: present
  when:
    - ansible_facts.distribution | lower == 'debian'
    - ansible_facts.distribution_major_version >= '12'

- block:
  # TODO(mattcrees): Remove once this gets into a versioned release:
  # https://github.com/ansible/ansible/pull/77754
  - name: Temporarily disable systemd-networkd
    become: true
    service:
      name: systemd-networkd
      enabled: no

  - name: enable systemd-networkd
    become: true
    service:
      name: systemd-networkd
      enabled: yes
  when: systemd_networkd_network or systemd_networkd_link or systemd_networkd_netdev

- name: start and enable systemd-resolved
  become: true
  service:
    name: systemd-resolved
    enabled: yes
    state: started
  when: systemd_networkd_enable_resolved

- name: replace /etc/resolv.conf with a symlink to the systemd-resolved stub
  become: true
  file:
    path: /etc/resolv.conf
    src: /run/systemd/resolve/stub-resolv.conf
    state: link
    force: yes
  when: systemd_networkd_symlink_resolv_conf

# vim: set ts=2 sw=2:
